### ISSUE TITLE
[功能请求]PPPOE重播 换IP

### ISSUE THREAD

**Issue by photkey** [wojiushixiaobai/ikuai-api#2]
![Snipaste_2022-07-21_22-52-07](https://user-images.githubusercontent.com/60434581/180245424-89e75daf-d1df-49fa-bb85-bf22892ab41f.png)

您好 大佬，请求个PPPOE重播 换IP的例子，不知道有没有可能实现一下。

**Comment by wojiushixiaobai** [comment]
- link: #f13b8ce1c42ee552b228df9e75b68b1e50b8a529

**Comment by wojiushixiaobai** [comment]
已实现
